###
GET http://localhost:1337/cart-items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjM3NDcxODUxLCJleHAiOjE2NDAwNjM4NTF9.rbk9h4uOJnySjqn_-98paS2DuU-JfuOAXq-hZYLpLk0

###
POST http://localhost:3000/api/login
Content-Type: application/json

 {
    "identifier":"andri@example.com",
    "password":"andri@example.com"
 }

###
POST http://localhost:1337/cart-items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjM3NDcxODUxLCJleHAiOjE2NDAwNjM4NTF9.rbk9h4uOJnySjqn_-98paS2DuU-JfuOAXq-hZYLpLk0
Content-Type: application/json

 {
    "product":2,
    "quantity":1
 }
###
POST http://localhost:1337/auth/local
Content-Type: application/json

 {
    "identifier":"andri@example.com",
    "password":"andri@example.com"
 }


###
http://localhost:1337/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NDcxMzE4LCJleHAiOjE2NDAwNjMzMTh9.6NNDaPNoAHZ0PxEQ31PZTAQUpGNzEWKnBuoQ45RPCgw


###
POST http://localhost:1337/auth/local/register
Content-Type: application/json

 {
     "username":"Charlie",
     "email":"charlie@example.com",
     "password":"charlie@example.com"
 }

###
GET https://ws.akademik.itb.ac.id/kelas?&kd_strata=eq.S2&semester=eq.2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaXNzaW9uIiwiZXhwIjoxNjQwOTcwMDAwfQ.sC08FyUv466d16NhmaRiU5FBlwoZpqGIlqlNWGXAQ1I

###
GET http://localhost:3000/api/user
